[build]
  publish = "public"
  command = ""

[[redirects]]
  from = "/dashboard"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/login"
  to = "/login.html"
  status = 200

[[redirects]]
  from = "/forgot-password"
  to = "/forgot_password.html"
  status = 200

[[redirects]]
  from = "/reset-password/:token"
  to = "/reset_password.html"
  status = 200
